require("core.keymaps")
require("core.opts")
require("core.abbr")
require("lazy-config")
require("config.lsp")
require("ui.statusline").setup({})
require("ui.tabline").setup()
require("ui.statuscolumn").setup()
