-- local set_hl = function(hlgroup, bg, fg, opts)
--     local hl_options = vim.tbl_extend('force', { bg = bg, fg = fg }, opts or {})
--     vim.api.nvim_set_hl(0, hlgroup, hl_options)
-- end
--
-- local colors = require('nordic.colors')
-- local palette = require('nordic.colors.nordic')
--
-- local M = {
--     setup = function()
--         set_hl('Normal', palette.black2, colors.none, {})
--         set_hl('NormalNC', palette.black2, colors.none, {})
--         set_hl('FloatBorder', palette.none, palette.gray2, {})
--         set_hl('VisualNOS', palette.none, palette.none, { reverse = true })
--         set_hl('Visual', palette.none, palette.none, { reverse = true })
--         set_hl('CMPMenu', palette.none, palette.white0_normal, {})
--         set_hl('CMPMenuSel', palette.blue2, palette.black0, {})
--         set_hl('CmpItemAbbrMatch', palette.none, palette.green.bright, {})
--         set_hl('CMPMenuBorder', palette.none, palette.gray5, {})
--         set_hl('CMPMenuThumb', palette.gray2, palette.none, {})
--         set_hl('CMPDoc', palette.none, palette.white0_reduce_blue, {})
--         set_hl('CMPDocBorder', palette.none, palette.blue0, {})
--         set_hl('NormalFloat', palette.black1, palette.white0_normal, {})
--         set_hl('TelescopeSelectionCaret', palette.none, palette.green.dim, {})
--         set_hl('TelescopePrompt', palette.magenta.base, palette.black0, {})
--         set_hl('CursorLine', palette.gray1, nil, {})
--         set_hl('CursorLineNr', palette.none, palette.yellow.bright, { bold = true })
--     end
-- }
--
-- return M
--
